version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - exit 0
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
volumes:
  node_modules: null
