services:
  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: tap-frontend-test:local
    container_name: tap-frontend-test
    ports:
      - 3456:3000
    volumes:
      - ./frontend:/app-src
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_VERSION=1.0.0
      - REACT_APP_RUNNING_IN_DOCKER=true
      - REACT_APP_CONTAINER_ID=tap-frontend-test
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_HOST=localhost
      - WDS_SOCKET_PORT=3456
    command: ["sh", "-c", "ls -la /app && ls -la /app/docker || echo 'Docker dir not found' && ls -la /app-src"]

volumes:
  frontend_node_modules:
    name: tap-frontend-node-modules-test