/**
 * Design System Adapter
 * 
 * Centralized adapter for all UI component dependencies.
 * This pattern prevents duplicate imports and standardizes component usage.
 * 
 * Usage:
 * import { Button, TextField, useMediaQuery } from '@design-system/adapter';
 */

// Material UI Core Components
import {
  AppBar,
  Autocomplete,
  Avatar,
  Badge,
  Box,
  Breadcrumbs,
  Button,
  Card,
  CardContent,
  CardHeader,
  CardActions,
  Checkbox,
  Chip,
  CircularProgress,
  Container,
  Dialog,
  DialogActions,
  DialogContent,
  DialogContentText,
  DialogTitle,
  Divider,
  Drawer,
  Fab,
  FormControl,
  FormControlLabel,
  FormGroup,
  FormHelperText,
  FormLabel,
  Grid,
  IconButton,
  InputLabel,
  LinearProgress,
  Link,
  List,
  ListItem,
  ListItemAvatar,
  ListItemIcon,
  ListItemText,
  Menu,
  MenuItem,
  Modal,
  Paper,
  Popover,
  Radio,
  RadioGroup,
  Select,
  Skeleton,
  Snackbar,
  Stack,
  Step,
  StepLabel,
  Stepper,
  Switch,
  Tab,
  Tabs,
  TextField,
  Toolbar,
  Tooltip,
  Typography,
} from '@mui/material';

// Material UI Hooks
import {
  useMediaQuery,
  useTheme,
} from '@mui/material';

// Material UI Icons (commonly used ones)
import {
  Add as AddIcon,
  ArrowBack as ArrowBackIcon,
  ArrowDropDown as ArrowDropDownIcon,
  CheckCircle as CheckCircleIcon,
  Close as CloseIcon,
  Delete as DeleteIcon,
  Edit as EditIcon,
  Error as ErrorIcon,
  ExpandMore as ExpandMoreIcon,
  Help as HelpIcon,
  Info as InfoIcon,
  Menu as MenuIcon,
  MoreVert as MoreVertIcon,
  Refresh as RefreshIcon,
  Save as SaveIcon,
  Search as SearchIcon,
  Settings as SettingsIcon,
  Warning as WarningIcon,
} from '@mui/icons-material';

// Custom components - these would be your enhanced/adapted components
import ErrorBoundary from '../design-system/adapted/core/ErrorBoundary';

// Re-export everything
export {
  // MUI Components
  AppBar,
  Autocomplete,
  Avatar,
  Badge,
  Box,
  Breadcrumbs,
  Button,
  Card,
  CardContent,
  CardHeader,
  CardActions,
  Checkbox,
  Chip,
  CircularProgress,
  Container,
  Dialog,
  DialogActions,
  DialogContent,
  DialogContentText,
  DialogTitle,
  Divider,
  Drawer,
  Fab,
  FormControl,
  FormControlLabel,
  FormGroup,
  FormHelperText,
  FormLabel,
  Grid,
  IconButton,
  InputLabel,
  LinearProgress,
  Link,
  List,
  ListItem,
  ListItemAvatar,
  ListItemIcon,
  ListItemText,
  Menu,
  MenuItem,
  Modal,
  Paper,
  Popover,
  Radio,
  RadioGroup,
  Select,
  Skeleton,
  Snackbar,
  Stack,
  Step,
  StepLabel,
  Stepper,
  Switch,
  Tab,
  Tabs,
  TextField,
  Toolbar,
  Tooltip,
  Typography,
  
  // MUI Hooks
  useMediaQuery,
  useTheme,
  
  // MUI Icons
  AddIcon,
  ArrowBackIcon,
  ArrowDropDownIcon,
  CheckCircleIcon,
  CloseIcon,
  DeleteIcon,
  EditIcon,
  ErrorIcon,
  ExpandMoreIcon,
  HelpIcon,
  InfoIcon,
  MenuIcon,
  MoreVertIcon,
  RefreshIcon,
  SaveIcon,
  SearchIcon,
  SettingsIcon,
  WarningIcon,
  
  // Custom components
  ErrorBoundary,
};