/**
 * React 18 Compatibility Adapters
 * 
 * This index file exports all adapter components for libraries
 * with React 18 compatibility issues.
 * 
 * Generated by react-compat adapter generator
 */

import reactJsonViewAdapters from './react-json-view-adapter';

// Export all adapters
export {
  reactJsonViewAdapters,
};

// Export individual adapters for convenience
export * from './react-json-view-adapter';
