/**
 * Content Security Policy Configuration
 * Generated by headers-configurator.js
 */

module.exports = {
  // CSP Directives
  'default-src': [''self''],
  'script-src': [''self'', ''unsafe-inline'', ''unsafe-eval''],
  'style-src': [''self'', ''unsafe-inline''],
  'img-src': [''self'', 'data:'],
  'font-src': [''self'', 'data:'],
  'connect-src': [''self'', ''],
  'frame-src': [''self''],
  'object-src': [''none''],
  'base-uri': [''self''],
  'form-action': [''self''],
  'frame-ancestors': [''self''],
  'upgrade-insecure-requests': [],
};

// Full CSP string for direct use
// default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'self' ; frame-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'self'; upgrade-insecure-requests
